version: '3'

services:
  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      - APP_ENV=${APP_ENV:-production}
    command: ./bin/client

  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-production}
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: ./bin/server
    restart: on-failure

  cron:
    build:
      context: ./
      dockerfile: docker/cron/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: ./bin/cron
    depends_on:
      - server
    restart: on-failure

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - client
      - server
    restart: on-failure
